name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: |
        go mod download
        go get github.com/ssrlive/proxypool/internal/app
        go get github.com/ssrlive/proxypool/api
        go get github.com/ssrlive/proxypool/internal/cron
      
    - name: Build
      run: make docker

    - name: Set variables
      run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_LOG=$(git log --pretty=format:"%s" | head -n 1)" >> $GITHUB_ENV
      shell: bash
      
    - name: Upload Release
      uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_LOG }}
        tag_name: ${{ env.TAG_NAME }}
        files: bin/*
        draft: true
        prerelease: true

    - uses: actions/upload-artifact@v2.3.1
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: build
        path: bin
